spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: "dGhpcy1pcy1hLXZhbGlkLXNlY3JldC1zdHJpbmctZm9yLUpXVC1leGFtcGxl"
  expiration: 1800000  # 30 minutes in milliseconds
